### PR TITLE
Implement clickable links

### PR DESCRIPTION
**Pull request by johnf**
First pass add implementing clickable links

### CODE REVIEW

**Comment by johnf** [comment]
Probably not quite ready to merge, looking for some feedback before I do any further work on it

**Comment by SmBe19** [comment]
I love this feature, I wanted to implement this myself but did not have the time to do it yet.

I don't know too much about Thunderbird extensions, so I can't give you feedback on the details of the code, but overall it looks fine.

Let me know when you think it's ready to merge or if you want feedback on something specific.

**Comment by SmBe19** [comment]
What would still need to be done for this to be ready to merge? I would love to merge this once it's ready.

**Comment by SmBe19** [comment]
I implemented it the master branch and fixed a few small issues. Thanks for your PR.

**Pull request closed without merging**
